require conf/machine/raspberrypi4-64.conf

RPI_KERNEL_DEVICETREE_OVERLAYS:append = " overlays/reTerminal.dtbo overlays/i2c3.dtbo"

KERNEL_MODULE_AUTOLOAD:rpi += "i2c-dev"

ENABLE_I2C = "1"

MENDER_STORAGE_TOTAL_SIZE_MB = "2048"

PREFERRED_VERSION_linux-raspberrypi ?= "6.6.%"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " \
    kernel-image \
    kernel-devicetree \
    seeed-linux-dtoverlays \
"
