# We have a conf directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mender-x86-uboot-efi"
BBFILE_PATTERN_meta-mender-x86-uboot-efi = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mender-x86-uboot-efi = "6"

LAYERVERSION_meta-mender-x86-uboot-efi = "1"
LAYERDEPENDS_meta-mender-x86-uboot-efi = "core meta-mender-explicit-wic"
LAYERSERIES_COMPAT_meta-mender-x86-uboot-efi = "scarthgap"

# Variable to reference this layer directory in recipes
LAYERDIR_meta-mender-x86-uboot-efi = "${LAYERDIR}"
