inherit image_types

# It is not possible to specify this using MENDER_IMAGE_BOOTLOADER_FILE/OFFSET,
# instead we use an append to "gptimg" to embed the bootloader

# STM32MP requires the disk image to be GPT for it to find the bootloader

IMAGE_CMD:gptimg:append:stcommon() {

    # Remove file generated by mender-part-images.bbclass
    rm "$wks"

    cat >> "$wks" <<EOF

# part fsbl1 --source rawcopy --fstype=ext4 --fsoptions "noauto" --part-name=fsbl1 --sourceparams="file=${DEPLOY_DIR_IMAGE}/arm-trusted-firmware/tf-a-stm32mp153a-ground4-mx-emmc.stm32" --ondisk mmcblk --part-type 0x8301 --fixed-size 256K --align 17
# part fsbl2 --source rawcopy --fstype=ext4 --fsoptions "noauto" --part-name=fsbl2 --sourceparams="file=${DEPLOY_DIR_IMAGE}/arm-trusted-firmware/tf-a-stm32mp153a-ground4-mx-emmc.stm32" --ondisk mmcblk --part-type 0x8301 --fixed-size 256K
part metadata1 --source rawcopy --fsoptions "noauto" --part-name=metadata1 --sourceparams="file=${DEPLOY_DIR_IMAGE}/arm-trusted-firmware/metadata.bin" --ondisk mmcblk --part-type 0x8301 --fixed-size 512K --align 30
part metadata2 --source rawcopy --fsoptions "noauto" --part-name=metadata2 --sourceparams="file=${DEPLOY_DIR_IMAGE}/arm-trusted-firmware/metadata.bin" --ondisk mmcblk --part-type 0x8301 --fixed-size 512K 
part fip-a  --source rawcopy --fstype=ext4 --fsoptions "noauto" --part-name=fip-a --sourceparams="file=${DEPLOY_DIR_IMAGE}/fip/fip-stm32mp153a-ground4-mx-trusted.bin" --ondisk mmcblk --part-type 19d5df83-11b0-457b-be2c-7559c13142a5 --uuid="4FD84C93-54EF-463F-A7EF-AE25FF887087" --fixed-size 4096K
part fip-b  --source rawcopy --fstype=ext4 --fsoptions "noauto" --part-name=fip-b --sourceparams="file=${DEPLOY_DIR_IMAGE}/fip/fip-stm32mp153a-ground4-mx-trusted.bin" --ondisk mmcblk --part-type 19d5df83-11b0-457b-be2c-7559c13142a5 --uuid="09C54952-D5BF-45AF-ACEE-335303766FB3" --fixed-size 4096K

part u-boot-env --source rawcopy --part-name=u-boot-env --sourceparams="file=${WORKDIR}/uboot.env" --ondisk "$ondisk_dev" --align $boot_env_align_kb --no-table
# part --source rootfs --rootfs-dir ${WORKDIR}/bootfs.${BB_CURRENTTASK} --ondisk "$ondisk_dev" --fstype=vfat --label boot --align $alignment_kb --fixed-size ${MENDER_BOOT_PART_SIZE_MB} --active $boot_part_params
part --source rootfs --ondisk "$ondisk_dev" --fstype=${ARTIFACTIMG_FSTYPE} --label primary --align $alignment_kb --fixed-size ${MENDER_CALC_ROOTFS_SIZE}k $exclude_path_options
part --source rootfs --ondisk "$ondisk_dev" --fstype=${ARTIFACTIMG_FSTYPE} --label secondary --align $alignment_kb --fixed-size ${MENDER_CALC_ROOTFS_SIZE}k $exclude_path_options
part --source rootfs --rootfs-dir ${IMAGE_ROOTFS}/data --ondisk "$ondisk_dev" --fstype=${ARTIFACTIMG_FSTYPE} --label data --align $alignment_kb --fixed-size ${MENDER_DATA_PART_SIZE_MB}
bootloader --ptable gpt
EOF

    echo "### Contents of STM32MP1 wks file ###"
    cat "$wks"
    echo "### End of contents of STM32MP1 wks file ###"

    # Call WIC
    outimgname="${IMGDEPLOYDIR}/${IMAGE_NAME}.$suffix"
    wicout="${IMGDEPLOYDIR}/${IMAGE_NAME}-$suffix"
    BUILDDIR="${TOPDIR}" wic create "$wks" --vars "${STAGING_DIR}/${MACHINE}/imgdata/" -e "${IMAGE_BASENAME}" -o "$wicout/" ${WIC_CREATE_EXTRA_ARGS}
    mv "$wicout/$(basename "${wks%.wks}")"*.direct "$outimgname"
}



# part fip  --source rawcopy --fstype=ext4 --fsoptions "noauto" --part-name=fip --sourceparams="file=/datadrive/gen3-dev/openstlinux-5.10-dunfell-mp1-21-03-31/build-openstlinuxweston-stm32mp1-henson/tmp-glibc/deploy/images/stm32mp1-henson/fip/fip-stm32mp157f-henson-mx-trusted.bin" --ondisk mmcblk --part-type 0x8301 --fixed-size 4096K
# part --source rawcopy --sourceparams="file=/datadrive/gen3-dev/openstlinux-5.10-dunfell-mp1-21-03-31/build-openstlinuxweston-stm32mp1-henson/tmp-glibc/work/stm32mp1_henson-ostl-linux-gnueabi/st-image-core/1.0-r0/uboot.env" --ondisk "$ondisk_dev" --align $boot_env_align_kb --no-table
# part --source rootfs --rootfs-dir /datadrive/gen3-dev/openstlinux-5.10-dunfell-mp1-21-03-31/build-openstlinuxweston-stm32mp1-henson/tmp-glibc/work/stm32mp1_henson-ostl-linux-gnueabi/st-image-core/1.0-r0/bootfs.image_gptimg --ondisk "$ondisk_dev" --fstype=ext4 --label bootfs --align $alignment_kb --fixed-size 64 --active $boot_part_params --part-type 0x8300
# part --source rootfs --ondisk "$ondisk_dev" --fstype=ext4 --label primary --align $alignment_kb --fixed-size 1523712k $exclude_path_options
# part --source rootfs --ondisk "$ondisk_dev" --fstype=ext4 --label secondary --align $alignment_kb --fixed-size 1523712k $exclude_path_options
# part --source rootfs --rootfs-dir /datadrive/gen3-dev/openstlinux-5.10-dunfell-mp1-21-03-31/build-openstlinuxweston-stm32mp1-henson/tmp-glibc/work/stm32mp1_henson-ostl-linux-gnueabi/st-image-core/1.0-r0/rootfs/data --ondisk "$ondisk_dev" --fstype=ext4 --label data --align $alignment_kb --fixed-size 1024
# bootloader --ptable gpt
# EOF