# Copyright 2026 Northern.tech AS

# We have a conf directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mender-nxp"
BBFILE_PATTERN_mender-nxp = "^${LAYERDIR}/"
BBFILE_PRIORITY_mender-nxp = "10"

LAYERDEPENDS_mender-nxp = "mender freescale-layer"

LAYERSERIES_COMPAT_mender-nxp = "wrynose"
