BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mender-qcom"
BBFILE_PATTERN_mender-qcom = "^${LAYERDIR}/"
BBFILE_PRIORITY_mender-qcom = "10"

LAYERSERIES_COMPAT_mender-qcom = "wrynose"
LAYERDEPENDS_mender-qcom = "mender qcom qcom-3rdparty"
