#!/bin/sh -e
echo "Notifying NV bootloader of successful upgrade" >&2
curslot=`nvbootctrl get-current-slot`
if ! nvbootctrl mark-boot-successful; then
    echo "ERR: could not restore boot-succesful status for slot: $curslot" >&2
    exit 1
fi
echo "Marked boot slot $curslot as successful" >&2
exit 0
