#!/bin/sh

# Note: only stderr is saved into Mender logs, for everything else use the logfile
script_name=$(basename "$0")
# Usually the script file is located at /data/mender/scripts/<script_name> but it might vary.
# We want to store logs at /data/mender/<script_name>.log
script_path=$(readlink -f "$0")
logfile="${script_path%/*}/../${script_name}.log"

mnt=
LABELCHARS="AB"
COPY_MACHINE_ID=@COPY_MACHINE_ID@

cleanup() {
    echo "Cleaning up" | tee -a $logfile
    [ -n "$mnt" ] || return
    for d in sys proc dev run; do
	if mountpoint -q "${mnt}/${d}"; then
	    umount "${mnt}/${d}" >/dev/null 2>&1 || true
	fi
    done
    if mountpoint -q "$mnt"; then
        umount "$mnt" >/dev/null 2>&1 || true
    fi
    rmdir "$mnt" >/dev/null 2>&1 || true
}

echo "Installing NVIDIA bootloader update payload - $(date)" | tee -a $logfile

if which tegra-boot-control >/dev/null 2>&1; then
    current_slot=`tegra-boot-control --current-slot`
else
    current_slot=`nvbootctrl get-current-slot`
fi
echo "Current boot slot: $current_slot" | tee -a $logfile
otherslot=`expr 1 - $current_slot`
cfglbl="\"RootfsPart${LABELCHARS:$otherslot:1}\""
devnam=`grep -h "$cfglbl:" /etc/mender/mender.conf /var/lib/mender/mender.conf | cut -d: -f2 | cut -d, -f1 | tr -d '" '`
echo "Device name for boot slot $otherslot: $devnam" | tee -a $logfile
if [ -z "$devnam" ]; then
    echo "ERR: could not determine device name for boot slot $otherslot" | tee -a $logfile >&2
    exit 1
fi
mnt=`mktemp -d -t nvbup.XXXXXX`
if [ -z "$mnt" -o ! -d "$mnt" ]; then
    echo "ERR: could not create directory for mounting install partition" | tee -a $logfile >&2
    exit 1
fi
echo "Mounting $devnam on $mnt" | tee -a $logfile
mount -o ro "$devnam" "$mnt"
if [ ! -d "${mnt}/opt/ota_package" ]; then
    echo "ERR: Missing /opt/ota_package directory in installed rootfs" | tee -a $logfile >&2
    cleanup
    exit 1
fi
# tegra-bootloader-update needs access to these filesystems,
# so bind-mount them into the new rootfs for the chroot
mount --bind /sys "${mnt}/sys"
mount --bind /proc "${mnt}/proc"
mount --bind /dev "${mnt}/dev"
# for tegra-bootinfo
mount --bind /run "${mnt}/run"

if ! chroot "${mnt}" /usr/bin/tegra-bootloader-update /opt/ota_package/bl_update_payload; then
    echo "ERR: bootloader update failed" | tee -a $logfile >&2
    cleanup
    exit 1
fi

if [ -n "$COPY_MACHINE_ID" ]; then
    echo "Copying machine ID" | tee -a $logfile
    curid=$(systemd-machine-id-setup --print)
    storedid=$(chroot "${mnt}" /usr/bin/tegra-bootinfo -n -v machine_id 2>/dev/null)
    if [ "$curid" != "$storedid" ]; then
        echo "Copying machine ID from $curid to $storedid" | tee -a $logfile
        chroot "${mnt}" /usr/bin/tegra-bootinfo --initialize 2>/dev/null
        chroot "${mnt}" /usr/bin/tegra-bootinfo -V machine_id "$curid"
    fi
fi
cleanup
echo "Successful bootloader update" | tee -a $logfile 
exit 0
