#!/bin/sh

LABELCHARS="AB"

echo "Verifying Tegra bootloader update"
curslot=`nvbootctrl get-current-slot`
cfglbl="\"RootfsPart${LABELCHARS:$curslot:1}\""
devnam=`grep -h "$cfglbl:" /etc/mender/mender.conf /var/lib/mender/mender.conf | cut -d: -f2 | cut -d, -f1 | tr -d '" '`
if [ -z "$devnam" ]; then
    echo "ERR: could not determine expected mender device name for boot slot $curslot" >&2
    exit 1
fi

# If the rootfs partitions are eMMC/SDcard device names, verify that
# the mender boot partition in U-Boot and the Tegra bootloader boot
# slot match.  If not, the Tegra bootloader update failed, and we
# need to have Mender roll us back.
if [ "${devnam##/dev/mmcblk}" != "${devnam}" ]; then
    bootpart=`fw_printenv -n mender_boot_part`
    if [ -z "$bootpart" ]; then
	echo "ERR: could not retrieve mender_boot_part from U-Boot env" >&2
	exit 1
    fi
    devnampart=`expr "${devnam##/dev/mmcblk*p}" \+ 0 2>/dev/null`
    if [ -z "$devnampart" ]; then
	echo "ERR: could not extract partition number from rootfs device name" >&2
	exit 1
    fi
    if [ $bootpart -ne $devnampart ]; then
	echo "Detected Tegra bootloader upgrade failure" >&2
	exit 1
    fi
fi
exit 0
