#!/bin/sh -e
echo "Notifying NV bootloader of successful upgrade"
curslot=`nvbootctrl get-current-slot`
if ! nvbootctrl mark-boot-successful; then
    echo "ERR: could not set boot-succesful status for slot: $curslot" >&2
    exit 1
fi
echo "Marked boot slot $curslot as successful"
exit 0
