#!/bin/sh
echo "Starting nvidia mender enter reboot redundant boot steps" >&2

set -e
num_slots=`nvbootctrl get-number-slots`
if [ $num_slots != 2 ]; then
    echo "Enabling A/B update mode using nv_update_engine" >&2
    nv_update_engine --enable-ab 1>&2
fi

new_boot_part=`fw_printenv -n mender_boot_part`

new_mender_boot_part_mountpoint=/tmp/new_mender_boot_part
ota_package_location=/opt/ota_package/bl_update_payload_current

echo "Mounting new install partition ${new_boot_part}" >&2
mkdir -p ${new_mender_boot_part_mountpoint}
mount -o ro /dev/mmcblk0p${new_boot_part} ${new_mender_boot_part_mountpoint}

echo "Mounting bl_update_payload from other partition"
mount --bind ${new_mender_boot_part_mountpoint}${ota_package_location} ${ota_package_location}

nv_update_engine --install 1>&2
# Should never get here, nv_update_engine will reboot on its own after successful update
echo "A failure occurred in nv_update_engine (rc $?).. nv_update_engine did not reboot" >&2

umount ${ota_package_location}
umount ${new_mender_boot_part_mountpoint}

exit 1
