# Layer for the Digilent Arty Z7-20 board (Zynq-7000)

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "arty-z7"
BBFILE_PATTERN_arty-z7 = "^${LAYERDIR}/"
BBFILE_PRIORITY_arty-z7 = "7"

LAYERDEPENDS_arty-z7 = "core xilinx"
LAYERSERIES_COMPAT_arty-z7 = "scarthgap"
