# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mender-raspberrypi-tpm"
BBFILE_PATTERN_meta-mender-raspberrypi-tpm = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mender-raspberrypi-tpm = "6"

LAYERDEPENDS_meta-mender-raspberrypi-tpm = "core"
LAYERSERIES_COMPAT_meta-mender-raspberrypi-tpm = "scarthgap"
