# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mender-raspberrypi-tryboot"
BBFILE_PATTERN_mender-raspberrypi-tryboot = "^${LAYERDIR}/"
BBFILE_PRIORITY_mender-raspberrypi-tryboot = "10"

LAYERDEPENDS_mender-raspberrypi-tryboot = "core raspberrypi"
LAYERSERIES_COMPAT_mender-raspberrypi-tryboot = "scarthgap"
