#!/bin/sh

# Inspired by "probe" in oe-init-build-env
if [ -n "$BASH_SOURCE" ]; then
    this_script=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
    this_script=$0
else
    this_script="$(pwd)/setup-environment"
fi

script_dir=$(dirname "$this_script")
script_dir=$(readlink -f "$script_dir")

if [ -d ${script_dir}/sources/meta-mender-community ]; then
    mender_community_dir=${script_dir}/sources/meta-mender-community
    layers_dir=sources
elif [ -d ${script_dir}/layers/meta-mender-community ]; then
    mender_community_dir=${script_dir}/layers/meta-mender-community
    layers_dir=layers
else
    echo "Sorry, can't seem to find meta-mender-community (tried sources, layers)"
    return 1
fi

build_dir=${script_dir}/build

target=""

targets=(
    "atmel"
    "amlogic"
    "beaglebone"
    "clearfog"
    "coral"
    "intel"
    "nxp"
    "octavo-osd32mp"
    "odroid"
    "qemu"
    "raspberrypi"
    "renesas"
    "rockchip"
    "sunxi"
    "tegra"
    "ti"
    "up"
    "variscite")

for i in ${targets[@]}
do
    if [[ $i == $1 ]]
    then
        target=$1
        break
    fi
done

if [ -z "${target}" ]; then
    echo "Sorry, it does not seem that *$1* is a valid target"
    echo ""

    printf "Supported targets are:\n"
    printf '%s\n' "${targets[@]}"
    return 1
fi

target_templates=${mender_community_dir}/meta-mender-${target}/templates


if [ -f ${script_dir}/${layers_dir}/poky/oe-init-build-env ]; then
    . ${script_dir}/${layers_dir}/poky/oe-init-build-env ${build_dir}
elif [ -f ${script_dir}/${layers_dir}/openembedded-core/oe-init-build-env ]; then
    . ${script_dir}/${layers_dir}/openembedded-core/oe-init-build-env ${build_dir}
else
    echo "Sorry, can't find oe-init-build-env."
    return 1
fi

# Common entries for Mender
cat ${mender_community_dir}/templates/local.conf.append >> ${build_dir}/conf/local.conf

# Board specific entries
cp ${target_templates}/bblayers.conf.sample ${build_dir}/conf/bblayers.conf
cat ${target_templates}/local.conf.append >> ${build_dir}/conf/local.conf

touch ${build_dir}/conf/mender_append_complete
