# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mender-seeed"
BBFILE_PATTERN_meta-mender-seeed = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mender-seeed = "6"

LAYERDEPENDS_meta-mender-seeed = "core raspberrypi mender"
LAYERSERIES_COMPAT_meta-mender-seeed = "scarthgap"
