#!/bin/sh
set -e

get_bootpart() {
    _cfglbl='"RootfsPartA"'
    _current_slot_cmd="nvbootctrl get-current-slot 2>/dev/null"
    _check=$(command -v nvbootctrl 2>/dev/null || true)
    if [ -z "${_check}" ]; then
        _check=$(command -v tegra-boot-control 2>/dev/null || true)
        if [ -z "${_check}" ]; then
            echo "ERR: Neither nvbootctrl nor tegra-boot-control were found!"
            exit 1
        fi
        _current_slot_cmd="tegra-boot-control --current-slot 2>/dev/null"
    fi

    _current_slot="$(${_current_slot_cmd})"
    if [ -z "${_current_slot}" ]; then
        echo "ERR: could not identify current boot slot" >&2
        echo "UNKNOWN"
        return
    fi

    if [ "${_current_slot}" = "1" ]; then
        _cfglbl='"RootfsPartB"'
    fi

    _devnam="$(grep -h "${_cfglbl}:" /etc/mender/mender.conf | tr -d '" ,' | grep -o '[0-9]\+$' || true)"
    if [ -z "${_devnam}" ]; then
      _devnam="$(grep -h "${_cfglbl}:" /var/lib/mender/mender.conf | tr -d '" ,' | grep -o '[0-9]\+$' || true)"
    fi

    if [ -z "${_devnam}" ]; then
        echo "ERR: Could not find partition number for ${_cfglbl}" >&2
        exit 1
    fi
    echo "${_devnam}"
}

quiet=
if [ "${1}" = "-n" ]; then
    quiet="yes"
    shift
    if [ -z "${1}" ]; then
        echo "ERR: missing var name with -n" >&2
        exit 1
    fi
fi

if [ -z "$1" ]; then
    bootpart="$(get_bootpart)"
    echo "mender_boot_part=${bootpart}"
    exit 0
fi

while [ -n "${1}" ]; do
    case "${1}" in
        mender_boot_part)
            bootpart="$(get_bootpart)"
            [ -n "${quiet}" ] || printf "%s=" "${1}"
            echo "${bootpart}"
            ;;
        mender_boot_part_hex)
            bootpart="$(get_bootpart)"
            bootpart_hex="$(echo "16o${bootpart}p" | dc)"
            [ -n "${quiet}" ] || printf "%s=" "${1}"
            echo "${bootpart_hex}"
            ;;
        mender_uboot_separator)
            [ -n "${quiet}" ] || printf "%s=" "${1}"
            echo "something other than just 1"
            ;;
        upgrade_available)
            [ -n "${quiet}" ] || printf "%s=" "${1}"
            if [ -e "/var/lib/mender/upgrade_available" ]; then
                echo "1"
            else
                echo "0"
            fi
            ;;
        mender_check_saveenv_canary)
            [ -n "${quiet}" ] || printf "%s=" "${1}"
            echo "0"
            ;;
        *)
           echo "ERR: no such variable: ${1}" >&2
           exit 1
    esac
    shift
done
