#!/bin/sh
echo "$(mender show-artifact): $(basename "$0") was called!" >&2

get_bootpart() {
	local current_slot=`nvbootctrl get-current-slot 2>/dev/null`
	if [ -z "$current_slot" ]; then
    		echo "ERR: could not identify current boot slot" >&2
    		echo "UNKNOWN"
    		return
    	fi
	echo "$current_slot"
}

reset_unbootable_status() {
	local AB="AB"
	local slot="Slot${AB:$1:1}"
	local varname="781e084c-a330-417c-b678-38e696380cb9-RootfsStatus${slot}"

	local f=$(mktemp)
	printf "\x00\x00\x00\x00" > $f
	efivar -n "${varname}" -f $f -w
	rm ${f}
}


current_slot=`get_bootpart`
echo "current_slot=$current_slot" >&2

next_slot=
if [ $current_slot = "0" ]; then
	next_slot="1"
else
	next_slot="0"
fi

echo "next_slot=$next_slot" >&2
nvbootctrl set-active-boot-slot $next_slot
oe4t-set-uefi-OSIndications
reset_unbootable_status $next_slot

exit 0
